use automation;

create table PAGES (
`PAGENAME` VARCHAR (50), -- SELECT
`PARENTID` VARCHAR (50), -- SELECT
`PAGEDESCRIPTION` VARCHAR (150), -- SELECT
PRIMARY KEY (`PAGENAME`)
);

create table GUIMAP (
`GUIMAPID` int (10) NOT NULL AUTO_INCREMENT,
`PAGENAME` VARCHAR (50) NOT NULL, 
`CONTROLTYPE` VARCHAR (50), -- SELECT (This is user friendly name for user)
`CONTROLNAME` VARCHAR (50), -- SELECT 
`CONTROLDESCRIPTION` VARCHAR (150), -- SELECT 
`FIELDNAME` VARCHAR (150), -- GEnerated from type+name
 PRIMARY KEY (`GUIMAPID`),
 CONSTRAINT fk_page FOREIGN KEY (`PAGENAME`)
 REFERENCES PAGES(`PAGENAME`) 
 ON DELETE CASCADE
 ON UPDATE CASCADE
 );



create table PROPERTIES (
`PROPERTYID` int (10) NOT NULL AUTO_INCREMENT,
`GUIMAPID` int (10) NOT NULL, 
`STANDARDCLASS`  VARCHAR (50), -- same as element type from guimap
`MAPPEDCLASS`  VARCHAR (50), 
`LOCATORVALUE` VARCHAR  (100) NOT NULL, -- Select
`LOCATORTYPE` VARCHAR (10) NOT NULL, -- Calculate based on value (xpath or id?)
`EXPROP1` VARCHAR  (100),
`EXPROP2` VARCHAR  (100),
`EXPROP3` VARCHAR  (100),
`EXPROP4` VARCHAR  (100),
`EXPROP5` VARCHAR  (100),
`EXPROP6` VARCHAR  (100),
`EXPROP7` VARCHAR  (100),
`EXPROP8` VARCHAR  (100),
`EXPROP9` VARCHAR  (100),
PRIMARY KEY (`PROPERTYID`),
CONSTRAINT fk_guimap FOREIGN KEY (GUIMAPID)
  REFERENCES GUIMAP(`GUIMAPID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

create table TYPES (
`CLASSID` int (10) NOT NULL AUTO_INCREMENT,
`CLASS` VARCHAR (20) NOT NULL,
`TYPE` VARCHAR (20) NOT NULL, 
`ABRV` VARCHAR (10) NOT NULL, 
`PROPERTYMAP` VARCHAR  (1000),
PRIMARY KEY (`CLASSID`)
);




insert into TYPES (`CLASS`, `TYPE`, `ABRV`)
values ('InputText','STANDARD','iTxt'),('Select','STANDARD','sel');


CREATE VIEW automation.entryform AS
SELECT a.CONTROLTYPE,a.CONTROLNAME, a.CONTROLDESCRIPTION,
b.LOCATORVALUE, b.LOCATORTYPE, b.PROPERTYMAP, 
b.EXPROP1, b.EXPROP2, b.EXPROP3, b.EXPROP4, b.EXPROP5,
b.EXPROP6, b.EXPROP7, b.EXPROP8, b.EXPROP9

FROM
automation.GUIMAP a, automation.PROPERTIES b;

CREATE VIEW automation.showtable AS
SELECT a.PAGENAME, a.CONTROLTYPE, a.CONTROLNAME, a.CONTROLDESCRIPTION, a.FIELDNAME,
b.PROPERTYID, b.GUIMAPID, b.STANDARDCLASS, b.MAPPEDCLASS, b.LOCATORVALUE, b.LOCATORTYPE
FROM
automation.GUIMAP a, automation.PROPERTIES b;
/*
ALTER TABLE PROPERTIES
DROP FOREIGN KEY fk_guimap;
ALTER TABLE GUIMAP
DROP FOREIGN KEY fk_page;

/*
delimiter //
CREATE TRIGGER updateElements AFTER INSERT ON GUIMAP
FOR EACH ROW 
BEGIN 
INSERT INTO PROPERTIES  VALUES (new.idemployee.40);
   END//;
delimiter ;


INSERT INTO PAGES
SET `pagename` = 'logon',
`parentid` = null,
`pagedescription` = "Login page";
*/





